# # FROM maven:3.8-openjdk-17
# FROM openjdk:11-jre

# # Create app directory.
# WORKDIR /app

# # Copy the application files to the app directory.
# COPY . .

# # Install the application.
# RUN mvn clean compile assembly:single
# RUN mvn package

# # Expose the port
# EXPOSE 5000

# # Run the application.
# CMD ["java", "-jar", "target/dssupplier-1.0-SNAPSHOT-jar-with-dependencies.jar"]